In [4]:
from pydantic import BaseModel, field_validator
import pandas as pd

# Bigger messy dataset (10 rows)
data = [
    {"name": "alice", "age": "30", "email": "ALICE@MAIL.COM "},
    {"name": "bob", "age": "22", "email": " BOB@mail.com"},
    {"name": "charlie", "age": "35", "email": "CHARLIE@mail.COM"},
    {"name": "david", "age": "28", "email": " DAVID@MAIL.com "},
    {"name": "eve", "age": "10", "email": "EVE@MAIL.COM"},
    {"name": "frank", "age": "19", "email": " frank@mail.com "},
    {"name": "grace", "age": "27", "email": "GRACE@mail.com"},
    {"name": "heidi", "age": "31", "email": "HEIDI@MAIL.COM "},
    {"name": "ivan", "age": "45", "email": " IVAN@mail.COM"},
    {"name": "judy", "age": "29", "email": "JUDY@mail.com "}
]

class User(BaseModel):
    name: str
    age: int
    email: str

    @field_validator("name")
    def clean_name(cls, v):
        return v.title()

    @field_validator("email")
    def clean_email(cls, v):
        return v.strip().lower()

# Convert raw → cleaned
cleaned_data = [User(**d).model_dump() for d in data]

# Create DataFrame
df = pd.DataFrame(cleaned_data)

# Show result
df

      name  age             email
0    Alice   30    alice@mail.com
1      Bob   22      bob@mail.com
2  Charlie   35  charlie@mail.com
3    David   28    david@mail.com
4      Eve   10      eve@mail.com
5    Frank   19    frank@mail.com
6    Grace   27    grace@mail.com
7    Heidi   31    heidi@mail.com
8     Ivan   45     ivan@mail.com
9     Judy   29     judy@mail.com

In [5]:
raw_df = pd.DataFrame(data)

print("Raw Data:")
display(raw_df)

print("\nCleaned Data:")
display(df)

Raw Data:

      name age             email
0    alice  30   ALICE@MAIL.COM
1      bob  22      BOB@mail.com
2  charlie  35  CHARLIE@mail.COM
3    david  28   DAVID@MAIL.com
4      eve  10      EVE@MAIL.COM
5    frank  19   frank@mail.com
6    grace  27    GRACE@mail.com
7    heidi  31   HEIDI@MAIL.COM
8     ivan  45     IVAN@mail.COM
9     judy  29    JUDY@mail.com

Cleaned Data:

      name  age             email
0    Alice   30    alice@mail.com
1      Bob   22      bob@mail.com
2  Charlie   35  charlie@mail.com
3    David   28    david@mail.com
4      Eve   10      eve@mail.com
5    Frank   19    frank@mail.com
6    Grace   27    grace@mail.com
7    Heidi   31    heidi@mail.com
8     Ivan   45     ivan@mail.com
9     Judy   29     judy@mail.com